### ISSUE TITLE
Incompatibility with `purs bundle`

### ISSUE THREAD

**Issue by maximedenes** [purescript/purescript-arrays#145]
The following line:

https://github.com/purescript/purescript-arrays/blob/d81e97137d2040f2fb42bf66124eb1d96e5dc1a7/src/Data/Array.js#L43

causes runtime errors when compiled with `purs bundle`, because `replicatePolyfill` gets eliminated as dead code.

I'm not sure if it is a `purs bundle` bug, since I don't understand exactly the spec of the code elimination it performs (in particular, what shapes of exports it supports).

**Comment by zyla** [comment]
I am experiencing it too.

An easy way to reproduce the issue is to run the test suite bundled and with `Array.prototype.fill` disabled:

```
$ pulp browserify -O --to output/test.js -I test --main Test.Main && node -e "delete Array.prototype.fill; require('./output/test.js').main();"
* Browserifying project in /home/zyla/w/o/purescript-arrays
* Building project in /home/zyla/w/o/purescript-arrays
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
* Browserifying...
* Browserified.
/home/zyla/w/o/purescript-arrays/output/test.js:873
  exports.replicate = typeof Array.prototype.fill === "function" ? replicate : replicatePolyfill;
                                                                               ^

ReferenceError: replicatePolyfill is not defined
    at PS.Data.Array (/home/zyla/w/o/purescript-arrays/output/test.js:873:80)
    at Object.1 (/home/zyla/w/o/purescript-arrays/output/test.js:1120:3)
    at o (/home/zyla/w/o/purescript-arrays/output/test.js:1:327)
    at r (/home/zyla/w/o/purescript-arrays/output/test.js:1:493)
    at Object.<anonymous> (/home/zyla/w/o/purescript-arrays/output/test.js:1:522)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by garyb** [comment]
Thanks for the reproduction case!
